apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-service-app
  labels:
    app: cloud-config-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-service-app
  template:
    metadata:
      labels:
        app: cloud-config-service-app
    spec:
      containers:
      - name: cloud-config-service-app
        image: foxx/cloud-config-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9296

---
kind: Service
apiVersion: v1
metadata:
  name: cloud-config-service-svc
spec:
  selector:
    app: cloud-config-service-app
  ports:
  - port: 80
    targetPort: 9296