apiVersion: v1
kind: ConfigMap
metadata:
  name: foxx-cm
data:
  foxx_service_address: http://foxx-0.foxx:8761/foxx

---

apiVersion: v1
kind: Service
metadata:
  name: foxx
  labels:
    app: foxx
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: foxx

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foxx
spec:
  serviceName: "foxx"
  replicas: 1
  selector:
    matchLabels:
      app: foxx
  template:
    metadata:
      labels:
        app: foxx
    spec:
      containers:
        - name: foxx
          image: foxx/service-registry:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: FOXX_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: foxx-cm
                  key: foxx_service_address

---

apiVersion: v1
kind: Service
metadata: 
  name: foxx-1b
  labels:
    app: foxx
spec:
  selector:
    app: foxx
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761